# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('permanent_address', models.CharField(max_length=250)),
                ('temporary_address', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('duration_stay', models.FloatField(max_length=4)),
                ('pan_no', models.IntegerField(default=None)),
                ('aadhar_no', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
