# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTO', '0003_vehicle_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_detail',
            name='engine_number',
            field=models.CharField(max_length=100),
        ),
    ]
