# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTO', '0004_auto_20180303_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_detail',
            name='registration_no',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
