# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTO', '0005_vehicle_detail_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_detail',
            name='registration_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
