# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RTO', '0006_auto_20180303_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_detail',
            name='registration_no',
        ),
    ]
