# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RTO', '0008_vehicle_detail_registration_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='police_officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_name', models.CharField(max_length=20)),
                ('accident_area', models.CharField(max_length=20)),
                ('accident_cause', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pollution_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('total_distance', models.IntegerField()),
                ('pollution_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_detail',
            name='registration_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pollution_check',
            name='vehicle_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTO.vehicle_detail'),
        ),
        migrations.AddField(
            model_name='police_officer',
            name='vehicle_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTO.vehicle_detail'),
        ),
    ]
