# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('user_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=250)),
                ('temporary_address', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('duration_stay', models.FloatField(max_length=4)),
                ('pan_no', models.IntegerField()),
                ('aadhar_no', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=13)),
                ('email_id', models.EmailField(max_length=25)),
            ],
        ),
    ]
