# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
