# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0002_personaldetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='duration_stay',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='aadhar_no',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='pan_no',
            field=models.CharField(max_length=20),
        ),
    ]
