# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0004_auto_20180308_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='chassis_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
