# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0005_auto_20180308_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentadd',
            old_name='user_personal',
            new_name='vehicle',
        ),
    ]
