# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mud', '0007_auto_20180316_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollutioncenter',
            old_name='next_service_data',
            new_name='next_service_date',
        ),
    ]
